name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: >
          This issue has been automatically marked as stale because it has not
          had recent activity. It will be closed if no further activity occurs.
          Please let us know if this issue is still valid!
        stale-pr-message: >
          This PR has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs.
          Please let us know if this PR is still need merging!
        stale-issue-label: 'stale'
        exempt-issue-label: 'High Priority'
        stale-pr-label: 'stale'
        exempt-pr-label: 'High Priority'
        days-before-stale: 365
        days-before-close: 90
